# NumPy practice

#### Udemy courses:
- [Python NumPy For Your Grandma](https://www.udemy.com/course/python-numpy-for-your-grandma/)
- [Learn NumPy Fundamentals (Python Library for Data Science)](https://www.udemy.com/course/python-numpy-fundamentals/)
- [Data Science: Python for Data Analysis Full Bootcamp](https://www.udemy.com/course/mastering-python-data-handling-analysis-and-visualization/)

### NumPy Library

In [1]:
import numpy as np

### Creating 1-D Arrays

In [2]:
new_arr = np.array([1, 2, 3, 4])
new_arr

array([1, 2, 3, 4])

In [3]:
np.zeros(4)

array([0., 0., 0., 0.])

In [40]:
ones_arr = np.ones(4)
ones_arr

array([1., 1., 1., 1.])

In [5]:
np.random.random(4)

array([0.12678118, 0.73171883, 0.05820371, 0.64694628])

In [37]:
prices = 100 + np.arange(5)
prices

array([100, 101, 102, 103, 104])

In [48]:
np.arange(start=1, stop=7, step=1)

array([1, 2, 3, 4, 5, 6])

### NumPy Array Basics

In [7]:
new_arr[0]

1

In [38]:
x = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
x.shape

(3, 3)

In [42]:
len(x)

3

In [46]:
x.size

9

In [43]:
x.ndim

2

In [44]:
type(x)

numpy.ndarray

In [45]:
x.dtype

dtype('int32')

### NumPy 1-D Operations

In [8]:
new_arr + ones_arr

array([2., 3., 4., 5.])

In [9]:
new_arr *2

array([2, 4, 6, 8])

### Math Functions with 1-D Array

In [10]:
new_arr.max()

4

In [11]:
new_arr.min()

1

In [12]:
new_arr.sum()

10

### Creating N-D Arrays or Matrices

In [13]:
x = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
x

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [14]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [47]:
np.full(shape=(3,4), fill_value="cat")

array([['cat', 'cat', 'cat', 'cat'],
       ['cat', 'cat', 'cat', 'cat'],
       ['cat', 'cat', 'cat', 'cat']], dtype='<U3')

In [16]:
r_arr = np.random.random((3, 4))

### Random

In [17]:
np.random.seed(0)

cube = np.random.randint(low=1, high=6, size=(5, 3))
mat = np.random.randint(10, size=(5, 3))

### Math with N-D Arrays

In [18]:
y = np.array([[2, 4, 6], [7, 8, 9], [10, 11, 12]])

In [19]:
x + y

array([[ 12,  24,  36],
       [ 47,  58,  69],
       [ 80,  91, 102]])

In [20]:
x.dot(y)

array([[ 460,  530,  600],
       [1030, 1220, 1410],
       [1600, 1910, 2220]])

In [21]:
y.max()

12

In [22]:
y.min()

2

#### .dot function

In [23]:
a = np.array([[2, 3], [4, 5]])
b = np.array([[10, 20], [11, 50]])

a * b
#a.dot(b)

array([[ 20,  60],
       [ 44, 250]])

### Broadcasting

In [24]:
a = np.array(
    [[[8, 6, 2, 3]],
    [[5, 9, 7, 5]],
    [[9, 7, 3, 7]]]
)
b = np.array([[9],[4]])
a + b


array([[[17, 15, 11, 12],
        [12, 10,  6,  7]],

       [[14, 18, 16, 14],
        [ 9, 13, 11,  9]],

       [[18, 16, 12, 16],
        [13, 11,  7, 11]]])

#### Compatibility
- A.shape (3, 1, 4)
- B.shape (   2, 1) 
-          ^  ^  ^
-        compatible

### Indexing 1-D arrays

In [25]:
new_arr[-1]

4

### Indexing for Matrices

In [26]:
y[0, 1]

4

In [27]:
y[0][1]

4

In [28]:
y [0:2, 1]

array([4, 8])

### Reshaping Arrays

In [29]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [30]:
b.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [31]:
b.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [32]:
b.T

array([[1, 4],
       [2, 5],
       [3, 6]])